# Custom Binning

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
import numpy as np

# Load dataset
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

# Preprocessing
data = data[['Age', 'Survived']].dropna()

data.head()

    Age  Survived
0  22.0         0
1  38.0         1
2  26.0         1
3  35.0         1
4  35.0         0

In [2]:
# create custom bins
age_bins = [0,18,60,100]
age_labels = ['Child','Adult','Senior']

In [3]:
data['Age Group'] = pd.cut(data['Age'], bins=age_bins,labels=age_labels, right=False)

In [4]:
data.sample(5)

      Age  Survived Age Group
11   58.0         1     Adult
273  37.0         0     Adult
184   4.0         1     Child
294  24.0         0     Adult
144  18.0         0     Adult