Categorical -> numerical (Ordinal.OHE,Target encoding,frequency encoding)
\n Discretization(binning)
\n target feature -> label encoding , label binarizer , multi label binarizar(to encode target col)

In [37]:
import numpy as np
import pandas as pd

In [38]:
df = pd.read_csv('customers.csv')

In [39]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

### 1. Ordinal Encoding

In [40]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)

In [42]:
X_train.head()

     review education
43     Poor        PG
23     Good    School
0   Average    School
21  Average        PG
18     Good    School

In [43]:
# specify order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [44]:
X_train = oe.fit_transform(X_train)
X_test =oe.transform(X_test)

In [45]:
X_train

array([[0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.]])

In [46]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [47]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [48]:
oe.n_features_in_

2

In [49]:
oe.inverse_transform(np.array([2,1]).reshape(1,2))

array([['Good', 'UG']], dtype=object)

In [50]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [51]:
# Handling unknown
# set unknown 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1
                    )
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4], df.iloc[:,-1], test_size=0.2)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

/opt/anaconda3/envs/ml-env/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])