Categorical -> numerical (Ordinal.OHE,Target encoding,frequency encoding)
\n Discretization(binning)
\n target feature -> label encoding , label binarizer , multi label binarizar(to encode target col)

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customers.csv')

In [4]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

### 1. Ordinal Encoding

In [5]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)

In [7]:
X_train.head()

     review education
43     Poor        PG
4   Average        UG
37  Average        PG
23     Good    School
30  Average        UG

In [8]:
# specify order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
X_train = oe.fit_transform(X_train)
X_test =oe.transform(X_test)

In [10]:
X_train

array([[0., 2.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [1., 2.]])

In [11]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [12]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [13]:
oe.n_features_in_

2

In [14]:
oe.inverse_transform(np.array([2,1]).reshape(1,2))

array([['Good', 'UG']], dtype=object)

In [15]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [16]:
# Handling unknown
# set unknown 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1
                    )
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4], df.iloc[:,-1], test_size=0.2)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

/opt/anaconda3/envs/ml-env/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

### 2. Rare Categories

In [17]:
# handling infrequent categories
X = np.array([['dog']*5 + ['cat']*20 + ['rabbit']*10 + ['snake']*3 + ['horse']*2],dtype=object).T

In [19]:
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [20]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [21]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [24]:
enc.transform(np.array(['cat','rabbit','horse','snake']).reshape(4,1))

array([[0.],
       [1.],
       [2.],
       [2.]])

In [25]:
enc = OrdinalEncoder(min_frequency=4).fit(X)

In [26]:
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [27]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

In [29]:
# handling missing data 

# Eg.
data = [['Cat'],[np.nan],['Dog'],[np.nan],['Horse'],['Rabbit']]

encoder = OrdinalEncoder(encoded_missing_value=-1)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [-1.]
 [ 2.]
 [ 3.]]